version: '3.0'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception_network
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    ports:
      - "9000:9000"
    restart: always
    networks:
      - inception_network
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/wordpress
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: always
    networks:
      - inception_network
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/wordpress

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/daypark/data/db'
  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/daypark/data/wp'

networks:
  inception_network:
